# gui/desktop/feature_toggles.py

import os

def is_feature_enabled(feature_name: str) -> bool:
    """
    Checks if a given feature is enabled based on environment variables.
    Feature names should be in uppercase, e.g., "ENABLE_RAG".
    """
    return os.getenv(feature_name, "false").lower() == "true"

# Define feature flags
ENABLE_RAG = "ENABLE_RAG"
ENABLE_VOICE_VIDEO_CALL = "ENABLE_VOICE_VIDEO_CALL"
ENABLE_MODEL_BUILDER = "ENABLE_MODEL_BUILDER"
ENABLE_FUNCTION_CALLING_TOOL = "ENABLE_FUNCTION_CALLING_TOOL"
ENABLE_WEB_SEARCH = "ENABLE_WEB_SEARCH"
ENABLE_WEB_BROWSING = "ENABLE_WEB_BROWSING"
ENABLE_IMAGE_GENERATION = "ENABLE_IMAGE_GENERATION"
ENABLE_MANY_MODELS_CONVERSATIONS = "ENABLE_MANY_MODELS_CONVERSATIONS"
ENABLE_RBAC = "ENABLE_RBAC"
ENABLE_MULTILINGUAL_SUPPORT = "ENABLE_MULTILINGUAL_SUPPORT"
ENABLE_PLUGINS = "ENABLE_PLUGINS"
ENABLE_OLLAMA_INTEGRATION = "ENABLE_OLLAMA_INTEGRATION"
ENABLE_CUSTOM_API_INTEGRATION = "ENABLE_CUSTOM_API_INTEGRATION"